tile_size: 48
stride: 48
top_percent: 0.15
min_score: 50.0
soft_min_score: 35.0
inset_left_pct: 0.1
inset_top_pct: 0.0
inset_right_pct: 0.1
inset_bottom_pct: 0.0
scale_factor: 1.0
image_name_template: "Y{y} X{x} Z{z} F{f}"
