FIRMWARE_NAME: "Marlin"
MACHINE_TYPE: "Ender-3"
baud_rate: 115200
max_x: 23500  # Maximum X dimension in steps
max_y: 22500  # Maximum Y dimension in steps
max_z: 36000   # Maximum Z dimension in steps
step_size: 1  # minimum distance that can be moved in 1 step
sample_positions:
  1: { x: 22.12, y: 200.00, z: 29.00 }
  2: { x: 33.47, y: 200.00, z: 29.00 }
  3: { x: 44.44, y: 200.00, z: 29.00 }
  4: { x: 53.28, y: 200.00, z: 29.00 }
  5: { x: 64.55, y: 200.00, z: 29.00 }
  6: { x: 75.70, y: 200.00, z: 29.00 }
  7: { x: 87.24, y: 200.00, z: 29.00 }
  8: { x: 98.60, y: 200.00, z: 29.00 }
  9: { x: 110.16, y: 200.00, z: 29.00 }
  10: { x: 122.00, y: 200.00, z: 29.00 }
  11: { x: 132.96, y: 200.00, z: 29.00 }
  12: { x: 144.46, y: 200.00, z: 29.00 }
  13: { x: 156.04, y: 200.00, z: 29.00 }
  14: { x: 167.44, y: 200.00, z: 29.00 }
  15: { x: 179.08, y: 200.00, z: 29.00 }
  16: { x: 190.72, y: 200.00, z: 29.00 }
  17: { x: 202.04, y: 200.00, z: 29.00 }
  18: { x: 213.36, y: 200.00, z: 29.00 }
  19: { x: 224.88, y: 200.00, z: 29.00 }
  20: { x: 224.88, y: 200.00, z: 29.00 }